export enum EScreens {
  ROOT_TABS = 'RootTabs',
  LOGIN_SCREEN = 'LoginScreen',
  SMS_CONFIRM_SCREEN = 'SMSConfirmScreen',
  AUTHORIZATION_STACK = 'AuthorizationStack',
  CARS_SCREEN = 'CarsScreen',
  FINES_SCREEN = 'FinesScreen',
  PAYMENTS_SCREEN = 'PaymentsScreen',
  SETTINGS_SCREEN = 'SettingsScreen',
  PROFILE_SCREEN = 'ProfileScreen',
  CARS_STACK = 'CarsStack',
  PROFILE_STACK = 'ProfileStack',
  FINES_STACK = 'FinesStack',
  PAYMENTS_STACK = 'PaymentsStack',
  SETTINGS_STACK = 'SettingsStack',
  INITIAL_SCREEN = 'InitialScreen',
  WEBVIEW_SCREEN = 'WebViewScreen',
  MODAL_LANGUAGE_SCREEN = 'ModalLanguageScreen',
  MODAL_EXIT_SCREEN = 'ModalExitScreen',
}
