export enum EScreens {
  ROOT_TABS = 'RootTabs',
  LOGIN_SCREEN = 'LoginScreen',
  SMS_CONFIRM_SCREEN = 'SMSConfirmScreen',
  AUTHORIZATION_STACK = 'AuthorizationStack',
  CARS_SCREEN = 'CarsScreen',
  SINGLE_CAR_SCREEN = 'SingleCarScreen',
  MODAL_DELETE_CAR = 'ModalDeleteCar',
  FINES_SCREEN = 'FinesScreen',
  PAYMENTS_SCREEN = 'PaymentsScreen',
  SETTINGS_SCREEN = 'SettingsScreen',
  PROFILE_SCREEN = 'ProfileScreen',
  CARS_STACK = 'CarsStack',
  PROFILE_STACK = 'ProfileStack',
  FINES_STACK = 'FinesStack',
  PAYMENTS_STACK = 'PaymentsStack',
  SETTINGS_STACK = 'SettingsStack',
  INITIAL_SCREEN = 'InitialScreen',
  WEBVIEW_SCREEN = 'WebViewScreen',
  MODAL_LANGUAGE_SCREEN = 'ModalLanguageScreen',
  MODAL_EXIT_SCREEN = 'ModalExitScreen',
  PROFILE_SETTINGS_SCREEN = 'ProfileSettingsScreen',
  MODAL_PHOTO_SCREEN = 'ModalPhotoScreen',
  MODAL_ADD_CAR = 'AddAutoModalScreen',
  SINGLE_FINE_SCREEN = 'SingleFineScreen',
  MODAL_IMAGE_VIEWER = 'ModalImageViewer',
}
