export const enTranslation = {
  translation: {
    version: 'Program version',
    tabs: {
      fines: 'Fines',
      cars: 'My cars',
      profile: 'Profile',
      payments: 'Payments',
      settings: 'Settings',
      osago: 'ОСАГО',
    },
    notifications: {
      noConnection: 'No internet connection',
    },
    languages: {
      ru: 'Русский',
      kg: 'Кыргыз тили',
      en: 'English',
    },
    cancel: 'Cancel',
    auth: {
      agree:
        'By clicking on the button, \nI agree to the terms of the Public Offer',
      getCode: 'Get the code',
      loginRegistration: 'Login / Registration',
      phoneInputLabel: 'Phone number',
      codeInputLabel:
        'A message with a code\nhas been sent to the number you provided\nEnter it:',
      apply: 'Confirm',
      changePhone: 'Change phone number',
      waitingToSendSms: 'Send SMS again after {{count}} seconds',
      resendSms: 'Send SMS again',
    },
    errors: {
      somethingWentWrong: 'Please try again',
      blackList: 'Your number is blocked',
    },
    cars: {
      title: 'My Cars',
      empty: 'Add a car\nto receive notifications',
      addAuto: 'Add a car',
      subTitle: 'List of cars for checking fines from the “Safe City” system',
      pin: {
        label: 'PIN (14-digits)',
        placeholder: 'PIN',
        error: 'Minimum 14 digits',
      },
      number: {
        label: 'Car number',
        placeholder: 'X0000XX, 00KG000XXX ',
        error: 'Car number is incorrect',
      },
      car: 'My car',
      deleteCar: 'Remove auto {{number}}',
      delete: 'Remove',
      inn: 'Owner Pin: {{inn}}',
    },
    fines: {
      title: 'Fines',
      happy: 'Congratulations!',
      empty: "We didn't find any fines",
      singleFineTitle: 'Fines',
      violationAmmount: 'Amount payable',
      violationPlace: 'Place',
      paymentStatusName: 'Paying',
      paymentNumber: 'Payment code',
      pay: 'Pay',
      unpaid: 'Unpaid',
      paid: 'Paid',
      selectType: 'Choose the type of fine',
      cameraFine: 'Safe City\nfines',
      policeFine: 'Traffic police patrol\nfines',
      paymentByCode: 'Pay by\npayment code',
      paymentCode: 'Payment code',
      paymentAmmount: 'Amount payable\nFilled in automatically',
      goToPay: 'Proceed to payment',
      codeNotFound: 'Payment code not found!',
      scanQrCode: 'Scan payment code',
      closeScanner: 'Close',
    },
    payments: {
      payByCard: 'Pay by card',
      payByMBank: 'Pay via Mbank',
      title: 'Payments',
      empty: 'No receipts found',
      receipt: 'Receipt',
      paymentInfo: 'Payment Information',
      subTitle:
        'Payments found: {{number}}\nView payments for the last 30 days. To view the entire payment history, activate the Premium subscription',
      serviceProviderDps: {
        type: 'Paying the DPS Fine',
        provider: 'Infosystems',
      },
      serviceProviderCity: {
        type: 'Paying the Safe City Fine',
        provider: 'Safe city (Infosystems)',
      },
      operationType: 'Type of transaction',
      article: 'Article',
      paymentNumber: 'Receipt number',
      serviceProvider: 'Service Provider',
      dateCreate: 'Create date',
      datePayment: 'Date of payment',
      protocolNumber: 'Protocol number',
      number: 'Car number',
      paymentSum: 'Amount payable',
    },
    settings: {
      title: 'Settings',
      registration: 'Filling out',
      pushLabel: 'PUSH notification',
      info: 'Information',
      questions: 'FAQ',
      userAgreement: 'Terms of use',
      privacyPolicy: 'Privacy Policy',
      eula: 'EULA',
    },
    profile: {
      title: 'Profile',
      finesPaid: 'Fines paid',
      settings: 'Settings',
      accumulatedPoints: 'Accumulated points',
      support: 'Support',
      selectLanguage: 'Language',
      exit: 'Exit',
      ru: 'Русский',
      kg: 'Кыргыз тили',
      name: 'Firstname',
      lastName: 'Lastname',
      editProfile: 'Edit profile',
      save: 'Save',
      selectAvatar: 'Select photo',
      fromGallery: 'Gallery',
      fromCamera: 'Camera',
      myCards: 'My credit cards',
      deleteAcc: 'Erase account?',
      deleteAccount: 'Erase account',
      delete: 'Remove',
      addCard: 'Add payment card',
      emptyCards: 'Cards not found',
      deleteCard: 'Delete card {{number}}?',
    },
    premium: {
      activate: 'Premium subscription',
      activateButton: 'Subscribe',
      title: {
        carsLimit: 'To add more 2 cars You need to activate a subscription',
        timeLimit:
          'You will be able to add a car in {{count}} мин. or activate the Premium subscription',
      },
      premium: 'Premium',
      subscribe: 'Subscribe',
      description:
        'up to 10 cars in the profile\npayment history\nstatus update 2 times a day',
      eula: 'EULA',
      agreement: 'Terms of use',
      restorePurchase: 'Restore Purchase',
    },
    osago: {
      title: 'Insurance',
      subTitle:
        'The insurance company shall make good the damage that you caused to someone as a result of a road traffic accident.',
      hasBranches: 'There are branches in the selected region',
      hasNotBranches: 'Only Courier delivery available',
      emptyDescription: "You don't have \n nany policies issued",
      applyOsago: 'New application',
      selectCity: 'Choose a region',
      statementScreen: {
        title: 'Application',
        totalInformation: 'General data',
        iAmTheOwner: 'Im the owner of the vehicle',
        iAmTheOwnerSubtitle:
          'If you are not the owner of the vehicle, you will need to attach a power of attorney with the right to alienate or a power of attorney for CMTPL registration',
        iHaveCard: 'I have a vehicle general inspection card for this year',
        carRegisteredInKr: 'Is the vehicle registered in the Kyrgyz Republic?',
        product: 'Product',
        selectedPeriod:
          'Select from the list the nperiod of validity of CMTPL insurance',
        email: 'Email address to which copies of documents will be sent',
        phone: 'Contact phone number',
        date: 'Date of birth',
        pin: 'PIN\n(14-digit code on the passport):',
        driverLicenseDate: 'Date of issue of the first driving licence',
        driver: 'Driver {{number}}',
        surname: 'Lastname',
        name: 'Firstname',
        secondName: 'Surname',
        class: 'Driver s Class:',
        addDriver: 'Add a driver',
        infoAboutCar: 'Vehicle data',
        carModel: 'Vehicle make',
        model: 'Model',
        carNumber: 'Number plate',
        yearOfIssue: 'Year of manufacture:',
        carType: 'Transport type',
        carVin: 'VIN, if right-hand drive - body number',
        policeInformation: 'Policy information',
        isPickUp: 'Do you need a policy delivered?',
        deliveryPaid: 'Delivery is paid separately!',
        isPickUpSubtitle: 'Delivery is paid separately.',
        whereToDeliver: 'Where to deliver the policy',
        pickUpOffice: 'Where is it convenient for you to pick up your policy?',
        IRead: 'I agree and accept ',
        rules: 'the terms',
        rulesTitle: 'Rules',
        conditionsTitle: 'Conditions',
        and: ' and ',
        conditions: 'conditions',
        registration:
          'of insurance and confirm the correctness of the specified data',
        loadDoc: 'Upload documents',
        questionTitle: 'Что такое класс водителя?',
        selectItemFromList: 'Select from the list',
        questionText:
          'Это система страховых коэффициентов, определяющих цену полиса в зависимости от того, были страховые случаи или нет. Если полис приобретается впервые, то водителю автоматически присваивается 3 класс. Чем выше класс, тем дешевле полис',
        error: 'Check the data entered',
        errorDoc: 'Не добавлены все документы',
      },
      documentsScreen: {
        title: 'Uploads documents',
        subTitle:
          'The images must be clear and the text must be easy to read. In case the data from the images is unreadable, the application will be cancelled.',
        idCart: 'ID card on both sides',
        driverLicense: 'Driver s licence on both sides',
        powerAttorney: 'Authorization to drive a motor vehicle',
        addPhoto: 'Upload',
        car: 'Vehicle',
        registration: 'Technical passport on both sides',
        registrationCard: 'General inspection card on both sides',
        drawUp: 'Complete',
      },
      infoPaymentScreen: {
        title: 'Information',
        policyholder: 'Driver / insurant',
        driver: 'Driver {{number}}',
        yes: 'Yes',
        no: 'No',
        isOwner: 'The applicant is the owner:',
        surname: 'Surname:',
        firstName: 'Firstname:',
        lastName: 'Lastname:',
        bithday: 'Date of birth:',
        pin: 'PIN (14-digit code on the passport):',
        driverClass: 'Driver s Class:',
        driveLicenseDate: 'Date of issue of the first driving licence:',
        amountInsurance: 'Insured value:',
        more: 'More',
        status: 'Status:',
        totalInformation: 'General data',
        insuranceType: 'Type of insurance:',
        numberDrivers: 'Number of drivers:',
        insurancePeriod: 'Duration of insurance:',
        phoneNumber: 'Phone number:',
        carData: 'Vehicle data',
        carModel: 'Vehicle make:',
        carNumber: 'Plate:',
        model: 'Model:',
        yearOfIssue: 'Year of manufacture:',
        carType: 'Transport type:',
        carVin: 'VIN, if right-hand drive - body number:',
        carRegisteredInKr: 'Is the vehicle registered in the KG:',
        technicalInspection: 'General inspection:',
        policyInfo: 'Информация о полисе:',
        receiptinfo: 'Информация о получении:',
        delivery: 'Доставка:',
        deliveryAddress: 'Delivery address:',
        placeReceipt: 'Policy place of receipt:',
        pay: 'Pay',
        cancelInformationDescription:
          'Средства будут возвращены в течении 5-7 дней',
      },
      osagoListScreen: {
        application: 'Application № {{number}}',
        policy: 'Policy № {{number}}',
        applicationDate: 'date of application: {{date}}',
        validDate: 'valid until: {{date}}',
      },
      policyScreen: {
        title: 'Policy',
      },
      calculationCostScreen: {
        title: 'Calculate the cost of the policy',
        deliveryCost: 'Delivery:',
        baseCost: 'Base cost:',
        commission: 'Processing fee:',
        totalCost: 'The total cost of the policy:',
      },
    },
  },
};
