export const enTranslation = {
  translation: {
    tabs: {
      fines: 'Fines',
      cars: 'My cars',
      profile: 'Profile',
      payments: 'Payments',
      settings: 'Settings',
    },
    notifications: {
      noConnection: 'Нет соединения с интернетом',
    },
    languages: {
      ru: 'Русский',
      kg: 'Кыргыз тили',
      en: 'English',
    },
    cancel: 'Отмена',
    auth: {
      agree: 'Нажимая на кнопку, я соглашаюсь с условиями \nПубличной оферты',
      getCode: 'Get the code',
      loginRegistration: 'Вход / Регистрация',
      phoneInputLabel: 'Номер телефона',
      codeInputLabel:
        'На указанный вами номер \nбыло отправлено сообщение с кодом. \nВведите его:',
      apply: 'Подтвердить',
      changePhone: 'Изменить номер телефона',
      waitingToSendSms: 'Можно повторить СМС через {{count}} сек',
      resendSms: 'Отправить СМС ещё раз',
    },
    errors: {
      somethingWentWrong: 'Что-то пошло не так. Попробуйте ещё раз',
      blackList: 'Ваш аккаунт заблокирован',
    },
    cars: {
      title: 'Мои авто',
      empty: 'Добавьте авто\nдля получения уведомлений',
      addAuto: 'Добавить авто',
      subTitle:
        'Списов автомобилей для проверки штрафов с системы "Безопасный город',
      pin: {
        label: 'ПИН (14-значный)',
        placeholder: 'ПИН ИНН',
        error: 'ПИН должен быть 14-значный',
      },
      number: {
        label: 'Номер автомобиля',
        placeholder: 'X0000XX, 00KG000XXX ',
        error: 'Номер не корректный',
      },
      car: 'Мое авто',
      deleteCar: 'Удалить авто {{number}}',
      delete: 'Удалить',
      inn: 'Пин владельца: {{inn}}',
    },
    fines: {
      title: 'Штрафы',
      happy: 'Поздравляем!',
      empty: 'Мы не нашли штрафов',
      singleFineTitle: 'Штраф',
      violationAmmount: 'Сумма штрафа',
      violationPlace: 'Место нарушения',
      paymentStatusName: 'Погашение штрафа',
      paymentNumber: 'Код оплаты',
      pay: 'Оплатить',
      unpaid: 'Неоплаченые',
      paid: 'Оплаченые',
      selectType: 'Выберите тип штрафа',
      cameraFine: 'ШТРАФЫ \nБезопасного города',
      policeFine: 'ШТРАФЫ \nДПС',
      paymentByCode: 'Оплатить\nпо коду оплаты',
      paymentCode: 'Код оплаты',
      paymentAmmount: 'Сумма к оплате \nЗаполняется автоматически',
      goToPay: 'Перейти к оплате',
      codeNotFound: 'Код оплаты не найден!',
      scanQrCode: 'Сканировать код оплаты',
      closeScanner: 'Закрыть',
    },
    payments: {
      payByCard: 'Оплатить картой',
      title: 'Платежи',
      empty: 'Не найдено ни одной квитанции',
      receipt: 'Квитанция',
      paymentInfo: 'Платежная информация',
      subTitle:
        'Найдено платежей: {{number}}\nОтображаются платежи за последние 30 дней. Для просмотра всей истории платежей активируйте Премиум подписку',
      serviceProviderDps: {
        type: 'Оплата штрафа ДПС',
        provider: 'Инфосистемс',
      },
      serviceProviderCity: {
        type: 'Оплата штрафа Безопасного города',
        provider: 'Безопасный город Инфосистемс',
      },
      operationType: 'Тип операции',
      article: 'Статья',
      paymentNumber: 'Номер квитанции',
      serviceProvider: 'Поставщик услуг',
      dateCreate: 'Дата создания',
      datePayment: 'Дата оплаты',
      protocolNumber: 'Номер протокола',
      number: 'Номер авто',
      paymentSum: 'Сумма к оплате',
    },
    settings: {
      title: 'Настройки',
      registration: 'Оформление',
      pushLabel: 'PUSH уведомления',
      info: 'Информация',
      questions: 'Часто задаваемые вопросы',
      userAgreement: 'Пользовательсое соглашение',
      privacyPolicy: 'Политика конденфициальности',
      eula: 'EULA',
    },
    profile: {
      title: 'Профиль',
      finesPaid: 'Оплачено штрафов',
      accumulatedPoints: 'Накопленных балов',
      support: 'Тех. поддержка',
      selectLanguage: 'Выбрать язык',
      exit: 'Выход',
      ru: 'Русский',
      kg: 'Киргизский',
      name: 'Имя',
      lastName: 'Фамилия',
      editProfile: 'Редактировать профиль',
      save: 'Сохранить',
      selectAvatar: 'Выбрать фото',
      fromGallery: 'Галлерея',
      fromCamera: 'Камера',
    },
  },
};
