export const enTranslation = {
  translation: {
    tabs: {
      fines: 'Fines',
      cars: 'My cars',
      profile: 'Profile',
      payments: 'Payments',
      settings: 'Settings',
    },
    notifications: {
      noConnection: 'No internet connection',
    },
    languages: {
      ru: 'Русский',
      kg: 'Кыргыз тили',
      en: 'English',
    },
    cancel: 'cancel',
    auth: {
      agree:
        'By clicking on the button, \nI agree to the terms of the Public Offer',
      getCode: 'Get the code',
      loginRegistration: 'Login / Registration',
      phoneInputLabel: 'Phone number',
      codeInputLabel:
        'A message with a code\nhas been sent to the number you provided\nEnter it:',
      apply: 'Confirm',
      changePhone: 'Change phone number',
      waitingToSendSms: 'Send SMS again after {{count}} seconds',
      resendSms: 'Send SMS again',
    },
    errors: {
      somethingWentWrong: 'Please try again',
      blackList: 'Your number is blocked',
    },
    cars: {
      title: 'My Cars',
      empty: 'Add a car\nto receive notifications',
      addAuto: 'Add a car',
      subTitle: 'List of cars for checking fines from the “Safe City” system',
      pin: {
        label: 'PIN (14-digits)',
        placeholder: 'PIN',
        error: 'Minimum 14 digits',
      },
      number: {
        label: 'Car number',
        placeholder: 'X0000XX, 00KG000XXX ',
        error: 'Car number is incorrect',
      },
      car: 'My car',
      deleteCar: 'Remove auto {{number}}',
      delete: 'Remove',
      inn: 'Owner Pin: {{inn}}',
    },
    fines: {
      title: 'Fines',
      happy: 'Congratulations!',
      empty: "We didn't find any fines",
      singleFineTitle: 'Fines',
      violationAmmount: 'Amount payable',
      violationPlace: 'Place',
      paymentStatusName: 'Paying',
      paymentNumber: 'Payment code',
      pay: 'Pay',
      unpaid: 'Unpaid',
      paid: 'Paid',
      selectType: 'Choose the type of fine',
      cameraFine: 'Safe City\nfines',
      policeFine: 'Traffic police patrol\nfines',
      paymentByCode: 'Pay by\npayment code',
      paymentCode: 'Payment code',
      paymentAmmount: 'Amount payable\nFilled in automatically',
      goToPay: 'Proceed to payment',
      codeNotFound: 'Payment code not found!',
      scanQrCode: 'Scan payment code',
      closeScanner: 'Close',
    },
    payments: {
      payByCard: 'Pay by card',
      title: 'Payments',
      empty: 'No receipts found',
      receipt: 'Receipt',
      paymentInfo: 'Payment Information',
      subTitle:
        'Payments found: {{number}}\nView payments for the last 30 days. To view the entire payment history, activate the Premium subscription',
      serviceProviderDps: {
        type: 'Paying the DPS Fine',
        provider: 'Infosystems',
      },
      serviceProviderCity: {
        type: 'Paying the Safe City Fine',
        provider: 'Safe city (Infosystems)',
      },
      operationType: 'Type of transaction',
      article: 'Article',
      paymentNumber: 'Receipt number',
      serviceProvider: 'Service Provider',
      dateCreate: 'Create date',
      datePayment: 'Date of payment',
      protocolNumber: 'Protocol number',
      number: 'Car number',
      paymentSum: 'Amount payable',
    },
    settings: {
      title: 'Settings',
      registration: 'Filling out',
      pushLabel: 'PUSH notification',
      info: 'Information',
      questions: 'FAQ',
      userAgreement: 'Terms of use',
      privacyPolicy: 'Privacy Policy',
      eula: 'EULA',
    },
    profile: {
      title: 'Profile',
      finesPaid: 'Fines paid',
      accumulatedPoints: 'Accumulated points',
      support: 'Support',
      selectLanguage: 'Language',
      exit: 'Exit',
      ru: 'Русский',
      kg: 'Кыргыз тили',
      name: 'Firstname',
      lastName: 'Lastname',
      editProfile: 'Edit profile',
      save: 'Save',
      selectAvatar: 'Select photo',
      fromGallery: 'Gallery',
      fromCamera: 'Camera',
      myCards: 'My credit cards',
      deleteAcc: 'Удалить аккаунт',
      delete: 'Удалить',
      addCard: 'Добавить карту',
    },
    premium: {
      activate: 'Ативировать премиум',
      title: {
        carsLimit:
          'Для добавления более 2-х авто неоходимо активировать премиум подписку',
        timeLimit:
          'Вы сможете добавить авто через {{count}} мин. или активировать преум подписку',
      },
    },
  },
};
