export const kgTranslation = {
  translation: {
    version: 'Программанын версиясы',
    tabs: {
      fines: 'Айыптар',
      cars: 'Машиналар',
      profile: 'Профиль',
      payments: 'Төлөмдөр',
      settings: 'Ырастоо',
      osago: 'ОСАГО',
    },
    notifications: {
      noConnection: 'Нет соединения с интернетом',
    },
    languages: {
      ru: 'Русский',
      kg: 'Кыргыз тили',
      en: 'English',
    },
    cancel: 'Жокко чыгаруу',
    auth: {
      agree:
        'Баскычты басуу менен мен Айкын офертанын шарттарына макулдугумду берем',
      getCode: 'Кодду алуу үчүн',
      loginRegistration: 'Кирүү / Каттоо',
      phoneInputLabel: 'Телефон номуру',
      codeInputLabel: 'Сиз көрсөткөн номурга \nкод менен билдирме \nжөнөтүлгөн',
      apply: 'Подтвердить',
      changePhone: 'Изменить номер телефона',
      waitingToSendSms: 'СМСти {{count}} кийин кайра жөнөтүү ',
      resendSms: 'СМСти кайра жөнөтүү',
    },
    errors: {
      somethingWentWrong: 'Что-то пошло не так. Попробуйте ещё раз',
      blackList: 'Сиздин номур бөгөттөлгөн',
    },
    cars: {
      title: 'Унааларым',
      empty: 'Билдирүүлөрдү алуу \nүчүн унааны кошуңуз',
      addAuto: 'Унааны кошуу',
      subTitle:
        '"Коопсуз шаар" тутумунан айыптарды текшерүү үчун автомобилдердин тизмеси',
      pin: {
        label: 'ЖИН (14-значный)',
        placeholder: 'ЖИН ИНН',
        error: 'ЖИН (14-значный)',
      },
      number: {
        label: 'Унаанын номуру',
        placeholder: 'X0000XX, 00KG000XXX ',
        error: 'Унаанын номурун текшериңиз',
      },
      car: 'Унааларым',
      deleteCar: 'Жоюу {{number}}',
      delete: 'Жоюу',
      inn: 'Унаа ээсинин ЖИН: {{inn}}',
    },
    fines: {
      title: 'Айыптар',
      happy: 'Куттуктайбыз!',
      empty: 'Биз айып тапкан жокпуз',
      singleFineTitle: 'Айыптар',
      violationAmmount: 'Төлөм',
      violationPlace: 'Место нарушения',
      paymentStatusName: 'Погашение штрафа',
      paymentNumber: 'Төлөм код',
      pay: 'Төлөө',
      unpaid: 'Төлөнбөгөндөр',
      paid: 'Төлөнгөндөр',
      selectType: 'Айыптык төлөмдүн түрүн тандаңыз',
      cameraFine: 'Коопсуз шаар\nАЙЫПТЫК ТӨЛӨМДӨРҮ',
      policeFine: 'ЖКК\nАЙЫПТЫК ТӨЛӨМДӨРҮ',
      paymentByCode: 'Төлөм код \nбелгиси боюнча төлөө',
      paymentCode: 'Төлөм код',
      paymentAmmount: 'Төлөнүүчү сумма\nАвтоматтык түрдө толтурулат',
      goToPay: 'Төлөм жүргүзүүгө өтүу',
      codeNotFound: 'Төлөө коду табылган жок!',
      scanQrCode: 'Код белгисин сканерлөө',
      closeScanner: 'Жокко чыгаруу',
    },
    payments: {
      payByCard: 'Карта менен төлөө',
      payByMBank: 'MBank аркылуу төлөө',
      title: 'Төлөмдөр',
      empty: 'Не Бир да дүмүрчөк табылган жок',
      receipt: 'Квитанция',
      paymentInfo: 'Төлөм маалыматы',
      subTitle:
        'Төлөмдөр табылды: {{number}}\nАкыркы 30 күндөгү төлөмдөр чагылдырылат. Төлөмдөрдүн бардык тарыхын кароо үчүн Премиум катталууну активдештириңиз.',
      serviceProviderDps: {
        type: 'ЖКК айыптарын төлөө',
        provider: 'Инфосистемс',
      },
      serviceProviderCity: {
        type: 'Коопсуз шаардын айыптарын төлөө',
        provider: 'Коопсуз шаар (ГП Инфосистемс)',
      },
      operationType: 'Операциянын тиби',
      article: 'Укук бузуунун беренеси',
      paymentNumber: 'Номер квитанции',
      serviceProvider: 'Кызмат көрсөтүүчү',
      dateCreate: 'Дата создания',
      datePayment: 'Төлөм күнү',
      protocolNumber: 'Номер протокола',
      number: 'Унаанын номуру',
      paymentSum: 'Төлөнүүчү сумма',
    },
    settings: {
      title: 'Ырастоо',
      registration: 'Жол-жоболоштуруу',
      pushLabel: 'PUSH Билдирүүлөр',
      info: 'Маалымат',
      questions: 'Көп берилүүчү суроолор',
      userAgreement: 'Колдонуучулук макулдашуу',
      privacyPolicy: 'Конфиденциалдуулук саясаты',
      eula: 'EULA',
    },
    profile: {
      title: 'Профиль',
      finesPaid: 'Төлөнгөн айыптар',
      settings: 'Ырастоо',
      accumulatedPoints: 'Балл топтоо',
      support: 'Техникалык колдоо',
      selectLanguage: 'Выбрать язык',
      exit: 'Чыгуу',
      ru: 'Русский',
      kg: 'Кыргыз тили',
      name: 'Аты',
      lastName: 'Фамилиясы',
      editProfile: 'Профилди өзгөртүп оңдоо',
      save: 'Сактоо',
      selectAvatar: 'Профиль сүрөтүн тандоо',
      fromGallery: 'Галереядан тандоо',
      fromCamera: 'Камера',
      myCards: 'Менин кредиттик карталарым',
      deleteAcc: 'Аккаунтту өчүрүү?',
      deleteAccount: 'Аккаунтту өчүрүү',
      delete: 'Өчүрүү',
      addCard: 'Карт кошуу',
      emptyCards: 'Сакталган карталарыңыз жок',
      deleteCard: 'Картты өчүрүү {{number}}?',
    },
    premium: {
      activate: 'Премиум активдештирүү',
      activateButton: 'Активдештирүү',
      title: {
        carsLimit: '2төн көп автону кошуу үчүн катталууну активдештирүү керек',
        timeLimit: 'Автону {{count}} мин. кийин кошо аласыз',
      },
      premium: 'Премиум',
      subscribe: 'Премиумдук активдештирүү',
      description:
        'профилдеги 10 унаага чейин \nтөлөм тарыхы \nстатусу күнүнө 2 жолу жаңыртылат',
      eula: 'EULA',
      agreement: 'Макулдашуу',
      restorePurchase: 'Калыбына келтирүү',
    },
    osago: {
      title: 'ОСАГО',
      subTitle:
        'Обязательное страхование по которому страховая компания возместит ущерб, нанесённый Вами другим участникам ДТП.',
      hasBranches: 'Есть филиалы в выбранном регионе',
      hasNotBranches: 'Доступна только курьерская доставка',
      emptyDescription: 'У вас нет \n оформленных полисов',
      applyOsago: 'Оформить ОСАГО',
      selectCity: 'Выберите город',
      statementScreen: {
        title: 'Заявка',
        totalInformation: 'Общие данные',
        iAmTheOwner: 'Я собственник автомобиля',
        iAmTheOwnerSubtitle:
          'Если вы не являетесь собственником автомобиля, вам потребуется загрузить доверенность с правом на отчуждение или доверенность на оформление ОСАГО',
        iHaveCard: 'У меня есть карта о техосмотре авто за этот год',
        carRegisteredInKr: 'Транспорт зарегистрирован в КР',
        product: 'Продукт',
        selectedPeriod: 'Выберите из списка срок действия ОСАГО',
        email: 'Адрес электронной почты, куда будут отправлены документы',
        phone: 'Контактный номер телефона',
        date: 'Дата рождения',
        pin: 'ПИН (14-значный код на паспорте):',
        driverLicenseDate: 'Дата выдачи первого водительского удостоверения',
        driver: 'Водитель {{number}}',
        surname: 'Фамилия',
        name: 'Имя',
        secondName: 'Отчество',
        class: 'Класс водителя:',
        addDriver: 'Добавить еще одного водителя',
        infoAboutCar: 'Данные о транспортном средстве',
        carModel: 'Марка',
        model: 'Модель',
        carNumber: 'Гос. номер',
        yearOfIssue: 'Год выпуска:',
        carType: 'Тип транспорта',
        carVin: 'VIN, если праворульное авто - номер кузова',
        policeInformation: 'Информация о полисе',
        isPickUp: 'Вам нужна доставка полиса?',
        deliveryPaid: 'Доставка оплачивается отдельно!',
        isPickUpSubtitle: 'Внимание! Это оплачивается отдельно.',
        whereToDeliver: 'Куда доставить полис',
        pickUpOffice: 'Где вам удобно будет забрать полис?',
        IRead: 'Я прочитал(а) и соглашаюсь со всеми ',
        rules: 'правилами',
        rulesTitle: 'Правила',
        conditionsTitle: 'Условия страхования',
        and: ' и ',
        conditions: 'условиями',
        registration: 'оформления полиса',
        loadDoc: 'Загрузить документы',
        questionTitle: 'Что такое класс водителя?',
        selectItemFromList: 'Выберите из списка',
        questionText:
          'Это система страховых коэффициентов, определяющих цену полиса в зависимости от того, были страховые случаи или нет. Если полис приобретается впервые, то водителю автоматически присваивается 3 класс. Чем выше класс, тем дешевле полис',
        error: 'Не заполнены обязательный поля',
      },
      documentsScreen: {
        title: 'Загрузка документов',
        subTitle:
          'Изображения должны быть четким, текст должен легко читаться. В случае если если данные с изображений будут нечитаемы - заявка будет аннулирована.',
        idCart: 'ID карта с обеих сторон',
        driverLicense: 'Водительское удостоверение с обеих сторон',
        powerAttorney: 'Доверенность на авто',
        addPhoto: 'Добавить',
        car: 'Автомобиль',
        registration: 'Техпаспорт с обеих сторон',
        registrationCard: 'Карточка техосмотра с обеих сторон',
        drawUp: 'Оформить',
      },
      infoPaymentScreen: {
        title: 'Информация',
        policyholder: 'Водитель/страхователь',
        driver: 'Водитель {{number}}',
        yes: 'Да',
        no: 'Нет',
        isOwner: 'Заявитель является собственником:',
        surname: 'Отчество:',
        firstName: 'Имя:',
        lastName: 'Фамилия:',
        bithday: 'Дата рождения:',
        pin: 'ПИН (14-значный код на паспорте):',
        driverClass: 'Класс водителя:',
        driveLicenseDate: 'Дата выдачи первого водительского удостоверения:',
        amountInsurance: 'Сумма страховки:',
        more: 'Подробнее',
        status: 'Статус:',
        totalInformation: 'Общие данные',
        insuranceType: 'Вид страхования:',
        numberDrivers: 'Количество водителей:',
        insurancePeriod: 'Период страхования:',
        phoneNumber: 'Номер телефона:',
        carData: 'Данные об автомобиле',
        carModel: 'Марка:',
        carNumber: 'Гос. номер:',
        model: 'Модель:',
        yearOfIssue: 'Год выпуска:',
        carType: 'Тип авто:',
        carVin: 'VIN, если праворульное авто - номер кузова:',
        carRegisteredInKr: 'Транспорт зарегистрирован в КР:',
        technicalInspection: 'Техосмотр:',
        policyInfo: 'Информация о полисе:',
        receiptinfo: 'Информация о получении:',
        delivery: 'Доставка:',
        deliveryAddress: 'Адрес доставки:',
        placeReceipt: 'Место получения полиса:',
        pay: 'Оплатить',
        cancelInformationDescription:
          'Средства будут возвращены в течении 5-7 дней',
      },
      osagoListScreen: {
        application: 'Заявка № {{number}}',
        policy: 'Полис № {{number}}',
        applicationDate: 'Дата заявки: {{date}}',
        validDate: 'Действителе до: {{date}}',
      },
      policyScreen: {
        title: 'Полис',
      },
      calculationCostScreen: {
        title: 'Расчет стоимости полиса',
        deliveryCost: 'Стоимость доставки:',
        baseCost: 'Базовая стоимость:',
        commission: 'Комиссия за эквайринг:',
        totalCost: 'Итоговая стоимость полиса:',
      },
    },
  },
};
